{"Q_ID": "1220110033", "S_NAME": "Exceptional & File Handli", "Q_NAME": "Divide using try catch", "Q_DESC": "The user will enter numerator and denominator. If the denominator is zero, an exception will be generated using throw statement and the denominator will be passed as parameter with the exception. The only catch block we have accepts integer parameter, hence the control will be shifted to this block and the statements in the catch block will be executed", "TESTCASE_1": "16 8\n###---###SEPERATOR---###---\nThe result of division is:2", "TESTCASE_2": "8 0\n###---###SEPERATOR---###---\nYou cannot enter 0 in denominator", "TESTCASE_3": "8 15\n###---###SEPERATOR---###---\nThe result of division is:0", "TESTCASE_4": "0\n###---###SEPERATOR---###---\n0", "TESTCASE_5": "0\n###---###SEPERATOR---###---\n0"}