#include <iostream>
#include<fstream>
using namespace std;
int main(void)
{
cout<<"Start"<<endl;
  try {
    char s;
    cout<<"Inside try block."<<endl;
    throw s;
    cout<<"This will not execute.";
  }
  catch(char i)
  {
    ofstream outfile("data");
    char i;
    cin>>i;
    outfile<<i;
    outfile.close();
    ifstream infile("data");
    infile>>i;
    cout<<"Caught an exception value is=";
    cout<<i<<endl;
  }
  cout<<"End";
  
	return 0;
}