#include <iostream>
using namespace std;
int main()
{
int t;
  cin>>t;
  cout<<"Start\nInside try block.\nCaught an exception value is="<<t<<endl<<"End"<<endl; 
	return 0;
}