#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{ float s;
  cin>>s;
  cout<<"Start"<<endl;
  try
  { cout<<"Inside try block."<<endl;
    throw s;
    cout<<"This will not execute.";
  }
  catch(float i)
  { cout<<"Caught an exception value is=";
    cout<<i<<endl;
  }
  cout<<"End";
return 0;
}