#include <iostream>
using namespace std;

int main()
{
	int num;
  	cin>>num;
  	
  	try
    {
      if(num<=0)
        throw num;
      
        for(int i=0;i<=num;i++)
        { 
          for(int j=0;j<i;j++)
          { 
            cout<<"* "; 
          }
          cout<<endl;
        }
    }
  	catch(int a)
    {
      cout<<"Exception occurred: value thrown";
    }
	return 0;
}