#include <iostream>
#include<fstream>
using namespace std;
int main(void)
{
cout<<"Start"<<endl;
  try {
    char s;
    cout<<"Inside try block."<<endl;
    throw s;
    cout<<"This will not execute.";
  }
  catch(char i){
    float a;
    cin>>a;
    cout<<"Caught an exception value is=";
    cout<<a<<endl;
  }
  cout<<"End";
	return 0;
}