#include<iostream>
using namespace std;
int main()
{
	float f;
  	cin>>f;
  	cout<<"Start"<<endl;
  	cout<<"Inside try block."<<endl;
  	cout<<"Caught an exception value is="<<f<<endl;
  	cout<<"End";
  	
}
