#include <iostream>
using namespace std;
int main()
{
float c;
  cin>>c;
  cout<<"Start"<<endl<<"Inside try block."<<endl;
  cout<<"Caught an exception value is="<<c;
  cout<<endl<<"End";
  
	return 0;
}