#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
  float n;
  cin>>n;
cout << "Start" << endl;
try {
char s;
cout << "Inside try block." << endl;

throw s;
cout << "This will not execute.";
}
catch(char i) {
cout << "Caught an exception value is="<<n;
//cout << i << endl;
}
cout << "\nEnd";
return 0;
}