#include <iostream>
using namespace std;
int main()
{
  float n;
  cin>>n;
  cout<<"Start"<<endl;
  cout<<"Inside try block."<<endl;
  cout<<"Caught an exception value is="<<n<<endl;
  cout<<"End";
	return 0;
}