#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
cout << "Start" << endl;
try {
char s[100];
  cin.getline(s,100);
cout << "Inside try block." << endl;
throw s;
}
catch(char const *c) {
cout << "Caught an exception value is=";
cout << c << endl;
}
cout << "End";
return 0;
}