#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
  string s;
  getline(cin,s);
cout << "Start" << endl;
try {
char a='a';
cout << "Inside try block." << endl;

throw a;
cout << "This will not execute.";
}
catch(char i) {
cout << "Caught an exception value is="<<s;
cout << endl;
}
cout << "End";
return 0;
}